### ISSUE TITLE
Support ASAN (-fsanitize=address) for xtensa target

### ISSUE THREAD

**Issue by paulreimer** [jcmvbkbc/crosstool-NG#51]
Not sure what is involved, but I know that ASAN support on x86 is amazing for finding tricky bugs, and I'd love to run it on my ESP32 debug builds.

I'm not sure what is involved in adding it for a new target. The current state seems to be a compiler warning (after adding `-fsanitize=address` to `CXXFLAGS`):
```
warning: -fsanitize=address not supported for this target
```

**Comment by jcmvbkbc** [comment]
It does not belong to the crosstool-ng, the gcc and libsanitizer bundled with it need to be modified so please move it to xtensa-gcc.
Also compiling with ASAN results in higher memory requirements: according to https://github.com/google/sanitizers/wiki/AddressSanitizerAlgorithm it requires 1/8 of used memory for its shadow map.

**Comment by paulreimer** [comment]
Thanks @jcmvbkbc, I have added it here:
https://github.com/jcmvbkbc/gcc-xtensa/issues/9
