### ISSUE TITLE
crosscompile in c unfortunately results in an error libgcc_s.so.1: error adding symbols: file in wrong format

### ISSUE THREAD

**Issue by onyx99** [jcmvbkbc/crosstool-NG#78]
hi,

i tried to crosscompile in c but unfortunately it results in an error

first i rebuilt a fresh toolchain

./rebuild-esp32s3-linux-wifi.sh

Building a toolchain for:
build  = x86_64-pc-linux-gnu
host   = x86_64-pc-linux-gnu
target = xtensa-esp32s3-linux-uclibcfdpic

and have set the path to the crosstool-NG binaries
export PATH=~/build/crosstool-NG/builds/xtensa-esp32s3-linux-uclibcfdpic/bin:$PATH

made a small example in c to compile

//test.c
#include <stdio.h>

int  main(void) {
  printf("test\n");
  return 0;
}

tried to compile it

xtensa-esp32s3-linux-uclibcfdpic-gcc test.c -o test

results in an error

/home/me/build/crosstool-NG/builds/xtensa-esp32s3-linux-uclibcfdpic/lib/gcc/xtensa-esp32s3-linux-uclibcfdpic/14.1.0/../../../../xtensa-esp32s3-linux-uclibcfdpic/bin/ld: /home/ellen/build/crosstool-NG/builds/xtensa-esp32s3-linux-uclibcfdpic/lib/gcc/xtensa-esp32s3-linux-uclibcfdpic/14.1.0/../../../../xtensa-esp32s3-linux-uclibcfdpic/lib/libgcc_s.so.1: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status

looks like it is pointing to a wrong libgcc maybe ?

tried to find it

sudo find / -name libgcc_s.so.1

/home/me/build/crosstool-NG/.build/xtensa-esp32s3-linux-uclibcfdpic/build/build-cc-gcc-final/gcc/libgcc_s.so.1
/home/me/build/crosstool-NG/builds/xtensa-esp32s3-linux-uclibcfdpic/xtensa-esp32s3-linux-uclibcfdpic/lib/libgcc_s.so.1
/home/me/build/crosstool-NG/builds/xtensa-esp32s3-linux-uclibcfdpic/xtensa-esp32s3-linux-uclibcfdpic/sysroot/lib/libgcc_s.so.1
/home/me/build/build-buildroot-esp32s3/target/lib/libgcc_s.so.1
/home/me/build/build-buildroot-esp32s3/host/xtensa-buildroot-linux-uclibc/sysroot/lib/libgcc_s.so.1
/var/spool/postfix/lib/x86_64-linux-gnu/libgcc_s.so.1

am i doing something wrong here?

**Comment by jcmvbkbc** [comment]
For the compiler to work correctly you need to provide the `XTENSA_GNU_CONFIG` environment variable, something like [this](https://github.com/jcmvbkbc/esp32-linux-build/blob/master/rebuild-esp32s3-linux-wifi.sh#L51).

**Comment by onyx99** [comment]
thanks!
